deployment:
  tasks:
    - export DEPLOYPATH=/home2/tjzufimy/public_html/website_2ccc7990
    - /bin/mkdir -p $DEPLOYPATH/ufc
    - /bin/mkdir -p $DEPLOYPATH/data
    - /bin/cp -R php/. $DEPLOYPATH/ufc/
    - /bin/cp -R data/. $DEPLOYPATH/data/
